name: Deploy Argo Workflow (Multi-Env)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout metadata repo
        uses: actions/checkout@v4
        with: 
            fetch-depth: 0 # Fetch all history for accurate diff

      - name: Detect workflow name, environment, image tag, and namespace
        id: detect
        run: |
          FILE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | head -n 1)
          echo "Detected file: $FILE"

          WORKFLOW_NAME=$(basename "$FILE" .yaml)
          echo "detected workflow name: $WORKFLOW_NAME"

          ENVIRONMENT=$(echo "$FILE" | cut -d '/' -f 1)
          echo "detected environment: $ENVIRONMENT"

          IMAGE_TAG=$(grep '^image_tag:' "$FILE" | awk '{ print $2 }')
          echo "detected image tag: $IMAGE_TAG"

          NAMESPACE=$(grep '^namespace:' "$FILE" | awk '{ print $2 }')
          echo "detected namespace: $NAMESPACE" 

          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "workflow_name=$WORKFLOW_NAME" >> $GITHUB_OUTPUT
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT

      - name: Select cluster based on environment
        run: |
            if [ "${{ steps.detect.outputs.environment }}" == "prod" ]; then
                echo "Setting context to prod cluster"
                echo "KUBECONFIG=/path/to/prod/kubeconfig" >> $GITHUB_ENV
            else
                echo "Setting context to dev cluster"
                echo "KUBECONFIG=/path/to/dev/kubeconfig" >> $GITHUB_ENV
            fi

      - name: Deploy Argo Workflow
        run: |
            kubectl get workflowtemplate ash-catmodel -n volcanoes -o json \
            | jq --arg param image_tag --arg value 11.22.33 '
            .spec.arguments.parameters |= map(
            if .name == $param then .value = $value else . end
            )' | kubectl replace -f -